# Generated by Django 5.2.1 on 2025-06-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='flash_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
