# Generated by Django 5.2.1 on 2025-05-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_slider_button_link_remove_slider_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Cake shop', max_length=255)),
                ('heading', models.CharField(default='Cakes and bakes from the house of Queens!', max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
