# Generated by Django 5.2.1 on 2025-06-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_flash_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount in currency (optional)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_cart_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum cart value to apply coupon (optional)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='times_used',
            field=models.PositiveIntegerField(default=0, help_text='How many times this coupon has been used'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of times this coupon can be used', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(decimal_places=2, help_text='Discount percentage, e.g., 10.00 for 10%', max_digits=5),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Expiry date of the coupon', null=True),
        ),
    ]
