# Generated by Django 5.2.1 on 2025-06-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_payment_id_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
