# Generated by Django 5.2.1 on 2025-06-08 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_orderitem_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_line1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='zip',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='state',
            new_name='province',
        ),
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
    ]
