# Generated by Django 5.2.1 on 2025-06-18 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_blogpost_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashsaleitem',
            old_name='offer',
            new_name='flash_sale',
        ),
        migrations.AlterUniqueTogether(
            name='flashsaleitem',
            unique_together={('flash_sale', 'product')},
        ),
    ]
