# Generated by Django 5.2.1 on 2025-05-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_instagramsection_maplocation_instagramimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='cakes_delivered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='cupcakes_baked',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='happy_customers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='years_of_baking',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title',
            field=models.CharField(default='About Cake Shop', max_length=255),
        ),
    ]
