# Generated by Django 5.2.1 on 2025-06-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_offer_flashsaleitem_flash_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplocation',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
