# Generated by Django 5.2.1 on 2025-06-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_address_line1_order_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationdetails',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='organizationdetails',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='organizationdetails',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='organizationdetails',
            name='youtube_url',
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('size', 'Size'), ('extra', 'Extra')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'unique_together': {('name', 'type')},
            },
        ),
    ]
