# Generated by Django 5.2.1 on 2025-05-23 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_aboutsection_cakes_delivered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutsection',
            old_name='cupcakes_baked',
            new_name='cakes_baked',
        ),
    ]
