# Generated by Django 5.2.1 on 2025-05-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_cupcakes_baked_aboutsection_cakes_baked'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Contact With us', max_length=100)),
                ('availability_note', models.CharField(default='Representatives or Advisors are available:', max_length=255)),
                ('weekday_hours', models.CharField(default='Mon-Fri: 5:00am to 9:00pm', max_length=100)),
                ('weekend_hours', models.CharField(default='Sat-Sun: 6:00am to 9:00pm', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='contact/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
