# Generated by Django 5.2.1 on 2025-06-08 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_organizationdetails_facebook_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoption',
            name='price',
        ),
        migrations.CreateModel(
            name='ProductOptionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productoption')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_prices', to='core.product')),
            ],
            options={
                'unique_together': {('product', 'option')},
            },
        ),
    ]
