# Generated by Django 5.2.1 on 2025-06-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_productoption_price_productoptionprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='default_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
