# Generated by Django 5.2.1 on 2025-05-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_order_coupon_code_order_discount_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('views', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(default='General', max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
