# Generated by Django 5.2.1 on 2025-06-01 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_newslettersubscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon_class',
        ),
    ]
