# Generated by Django 5.2.1 on 2025-06-01 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_specialoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialoffer',
            name='link',
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='special_offers', to='core.product'),
            preserve_default=False,
        ),
    ]
