# Generated by Django 5.2.1 on 2025-06-01 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_specialoffer_link_specialoffer_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialoffer',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='specialoffer',
            name='product',
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.coupon'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
