# Generated by Django 5.2.1 on 2025-06-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_specialoffer_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('description', models.TextField(blank=True)),
                ('working_hours_mon_fri', models.CharField(default='08:00 am – 08:30 pm', max_length=50)),
                ('working_hours_sat', models.CharField(default='10:00 am – 16:30 pm', max_length=50)),
                ('working_hours_sun', models.CharField(default='10:00 am – 16:30 pm', max_length=50)),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
            ],
        ),
    ]
